# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_test', '0003_auto_20160707_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv_name', models.CharField(max_length=32, verbose_name='Interval Name')),
                ('iv_dist', models.IntegerField(verbose_name='Interval Distance (Semitones)')),
            ],
            options={
                'ordering': ['iv_dist'],
            },
        ),
        migrations.RenameModel(
            old_name='Intervals',
            new_name='IntervalList',
        ),
    ]
