# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr_name', models.CharField(max_length=32)),
                ('vr_bot', models.CharField(max_length=3)),
                ('vr_top', models.CharField(max_length=3)),
            ],
        ),
    ]
