# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(max_length=32, verbose_name='Scale Name')),
                ('sc_root', models.CharField(max_length=2, verbose_name='Scale Root')),
                ('sc_type', models.BooleanField(verbose_name='Scale Type')),
            ],
        ),
        migrations.AlterField(
            model_name='voicerange',
            name='vr_bot',
            field=models.CharField(max_length=3, verbose_name='Voice Range Bottom'),
        ),
        migrations.AlterField(
            model_name='voicerange',
            name='vr_name',
            field=models.CharField(max_length=32, verbose_name='Voice Range Name'),
        ),
        migrations.AlterField(
            model_name='voicerange',
            name='vr_top',
            field=models.CharField(max_length=3, verbose_name='Voice Range Top'),
        ),
    ]
