# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_test', '0002_auto_20160707_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['sc_type', 'sc_root']},
        ),
        migrations.AlterModelOptions(
            name='voicerange',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='scale',
            name='sc_type',
            field=models.BooleanField(verbose_name='Diatonic (Major)'),
        ),
    ]
