# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_test', '0004_auto_20160711_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='iv_abrv',
            field=models.CharField(default='', max_length=2, verbose_name='Interval Abbreviation'),
            preserve_default=False,
        ),
    ]
