# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_test', '0005_interval_iv_abrv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntervalList',
            new_name='IntervalManager',
        ),
    ]
